"""ACTION + VERIFY steps — post the verdict to GitHub as a real issue.

Uses GitHub's own REST API (api.github.com) — the correct tool for writing to
GitHub; no browser automation.

Credential model: the GitHub token is supplied PER REQUEST by whoever triggers
the investigation (API/CLI/dashboard). It is never read from the environment,
never stored in the database, never logged, and never returned in a response —
it lives only in-memory for the duration of this call. If the caller provides
no token (or no owner/repo), the step is skipped cleanly and logged — never
faked. VERIFY then GETs the created issue back to confirm it actually exists
before the ACTION step is marked complete.
"""

from __future__ import annotations

from typing import Any

import httpx

from .db import Database
from .events import log_event

GITHUB_API = "https://api.github.com"
ISSUE_TIMEOUT = 30.0


def _format_comparison_table(comparison: dict) -> str:
    lines = [
        "| Metric | Baseline | Candidate | Δ absolute | Δ % |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, m in (comparison.get("metrics") or {}).items():
        pct = "n/a" if m.get("percentage_delta") is None else f"{m['percentage_delta']:+.2f}%"
        lines.append(
            f"| {name} | {m.get('baseline')} | {m.get('candidate')} | {m.get('absolute_delta', 0):+g} | {pct} |"
        )
    return "\n".join(lines)


def _format_health(comparison: dict) -> str:
    health = comparison.get("environment_health") or {}
    rows = []
    for env in ("baseline", "candidate"):
        h = health.get(env) or {}
        rows.append(
            f"| {env} | {'✅' if h.get('build_success') else '❌'} | {'✅' if h.get('startup_success') else '❌'} |"
        )
    return "\n".join(["| Environment | Build | Startup |", "| --- | --- | --- |", *rows])


def build_issue_body(
    dependency_name: str,
    from_version: str,
    to_version: str,
    comparison: dict,
    decision: dict,
    research: dict | None = None,
    scores: dict | None = None,
) -> str:
    score_line = ""
    if scores:
        score_line = (
            f"**Compatibility score:** overall {scores.get('overall_score')} "
            f"(functional {scores.get('functional_score')}, performance {scores.get('performance_score')})\n\n"
        )
    research_section = ""
    if research and research.get("urls"):
        research_section = (
            "## Web research evidence\n"
            + "\n".join(f"- {u}" for u in research["urls"][:6])
            + "\n\n"
        )
    verdict = decision.get("verdict", "UNKNOWN")
    reasons = "\n".join(f"- {r}" for r in decision.get("reasons", []))
    return f"""## Alfred release-impact verdict: {verdict}

**Dependency:** `{dependency_name}` {from_version} → {to_version}
{score_line}### Environment health

{_format_health(comparison)}

### Measured comparison

{_format_comparison_table(comparison)}

### Why

{reasons}

**Recommendation:** {decision.get("recommendation", "n/a")}
{research_section}
---
*Generated by Alfred — every number above comes from real container execution
of the same repo against both dependency versions (baseline vs candidate).
Decision source: {decision.get("decided_by", "unknown")}.*
"""


def post_github_issue(
    db: Database,
    investigation_id: str,
    github_token: str | None,
    github_owner: str | None,
    github_repo: str | None,
    dependency_name: str,
    from_version: str,
    to_version: str,
    comparison: dict,
    decision: dict,
    research: dict | None = None,
    scores: dict | None = None,
) -> dict:
    """POST the issue, then GET it back to VERIFY it exists.

    ``github_token``/``github_owner``/``github_repo`` are the per-request
    credentials supplied by the caller — never persisted, never logged.
    """
    if not github_token:
        log_event(
            db, investigation_id, "ACTION",
            "no GitHub token provided for this investigation; skipping issue creation (never faked)",
            level="warn",
        )
        return {"skipped": True, "skip_reason": "no GitHub token provided for this investigation", "success": False, "verified": False}
    if not github_owner or not github_repo:
        log_event(
            db, investigation_id, "ACTION",
            "github_owner/github_repo not provided for this investigation; skipping issue creation",
            level="warn",
        )
        return {"skipped": True, "skip_reason": "github_owner/github_repo not provided for this investigation", "success": False, "verified": False}

    owner, repo = github_owner, github_repo

    title = f"[Alfred] {dependency_name} {from_version} → {to_version}: {decision.get('verdict', 'verdict')}"
    body = build_issue_body(
        dependency_name, from_version, to_version, comparison, decision, research, scores
    )
    url = f"{GITHUB_API}/repos/{owner}/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    log_event(db, investigation_id, "ACTION", f"POST {url}")
    try:
        resp = httpx.post(url, headers=headers, json={"title": title, "body": body}, timeout=ISSUE_TIMEOUT)
    except Exception as exc:  # noqa: BLE001
        log_event(db, investigation_id, "ACTION", f"issue creation request failed: {exc}", level="error")
        return {"skipped": False, "success": False, "verified": False, "error": str(exc)}

    if resp.status_code not in (200, 201):
        log_event(db, investigation_id, "ACTION", f"GitHub API returned {resp.status_code}: {resp.text[:300]}", level="error")
        return {"skipped": False, "success": False, "verified": False, "error": f"HTTP {resp.status_code}: {resp.text[:300]}"}

    data = resp.json()
    issue_url = data.get("html_url")
    issue_number = data.get("number")
    log_event(db, investigation_id, "ACTION", f"issue #{issue_number} created: {issue_url}")

    # VERIFY — GET the issue back to confirm it actually exists.
    verify_url = f"{GITHUB_API}/repos/{owner}/{repo}/issues/{issue_number}"
    try:
        vresp = httpx.get(verify_url, headers=headers, timeout=ISSUE_TIMEOUT)
        verified = vresp.status_code == 200 and vresp.json().get("number") == issue_number
    except Exception as exc:  # noqa: BLE001
        log_event(db, investigation_id, "VERIFY", f"verification request failed: {exc}", level="warn")
        verified = False

    if verified:
        log_event(db, investigation_id, "VERIFY", f"issue #{issue_number} verified on GitHub")
    else:
        log_event(db, investigation_id, "VERIFY", f"issue #{issue_number} could not be verified", level="warn")

    return {
        "skipped": False,
        "success": True,
        "verified": verified,
        "issue_url": issue_url,
        "issue_number": issue_number,
    }
